config/urls.py
from django.contrib import admin
from django.urls import path, include
from music import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),
    # this gives us all the registration urls
    # we are particularly interested in 'accounts/login' and 'accounts/logout'
    # arguments, in order:
    # url pattern that user visits
    # view that's called
    # context(optional, if you are passing data from the db)
    # name argument(a nickname/shortcut used to refer to this path in other places in the project)
    path('', views.index, name='home'),
    path('album/<int:pk>', views.album_detail, name='album-detail'),
    path('album/new', views.create_album, name='album-new'),
    path('album/new_itunes', views.create_itunes_album, name='album-new-itunes'),
    path('album/<int:pk>/edit', views.album_edit, name='album-edit'),
    path('album/<int:pk>/delete', views.album_delete, name='album-delete'),
    path('album/<int:pk>/delete_detail', views.album_delete_detail, name='album-delete-detail'),
]

music/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.core.validators import MaxValueValidator, MinValueValidator
from datetime import date

# Create your models here.
CURRENT_YEAR = date.today().year


class User(AbstractUser):
    # extends Django's built-in AbstractUser class
    # adding optional fields for additional user info
    bio = models.TextField(max_length=500, blank=True, null=True)
    location = models.CharField(max_length=30, blank=True, null=True)
    birth_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.username


class Artist(models.Model):
    name = models.CharField(max_length=200, unique=True)
    members = models.CharField(max_length=200, blank=True, null=True)
    year_formed = models.IntegerField(validators=[MinValueValidator(1900), MaxValueValidator(CURRENT_YEAR)], blank=True, null=True)

    def __str__(self):
        return self.name


class Album(models.Model):
    # set full genre all caps = two letter abbrev
    ALT_METAL = 'AM'
    ALT_ROCK = 'AR'
    ROCK = 'RK'
    METAL = 'MT'

    # then genre_choices is list of tuples (full genre all caps = full genre for page display)
    GENRE_CHOICES = [(ALT_METAL, 'Alternative Metal'), (ALT_ROCK, 'Alternative Rock'), (ROCK, 'Rock'), (METAL, 'Metal')]

    title = models.CharField(max_length=200, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    release_date = models.DateField(blank=True, null=True)
    genre = models.CharField(max_length=2, choices=GENRE_CHOICES, null=True, blank=True)
    album_art = models.URLField(blank=True, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=2)

    def __str__(self):
        artists = self.artist_from_songs
        return f'{self.title}' + ' by ' + ', '.join({artist.name for artist in artists})

    @property
    def artist_from_songs(self):
        return [song.artist for song in self.songs.all()]


class Song(models.Model):
    title = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist, on_delete=models.CASCADE, related_name='songs')
    album = models.ForeignKey(Album, on_delete=models.CASCADE, related_name='songs')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.title} by {self.artist}'

music/forms.py
from django import forms
from .models import Artist, Album, Song


class ArtistForm(forms.ModelForm):
    class Meta:
        model = Artist
        fields = ('name', 'year_formed')


class AlbumForm(forms.ModelForm):
    class Meta:
        model = Album
        fields = ('title', 'release_date', 'genre')


class SongForm(forms.ModelForm):
    class Meta:
        model = Song
        fields = ('title', 'artist', 'album')

music/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import User, Album, Artist, Song
from .forms import AlbumForm
from django.contrib import messages
# from .consume import data_album
import json

# Create your views here.
# This is where actions happen. They are triggered by the user (or an AJAX request with JS)visiting a url.


def index(request):
    albums = Album.objects.all()
    form = AlbumForm()
    context = {
        'form': form,
        'albums': albums,
    }
    # context is data from the database
    return render(request, 'music/index.html', context)


def album_detail(request, pk):
    album = get_object_or_404(Album, pk=pk)
    return render(request, 'music/album_detail.html', {'album': album})


def create_album(request):
    if request.method == 'POST':
        form = AlbumForm(request.POST)
        if form.is_valid():
            album = form.save(commit=False)
            album.save()
            messages.success(request, 'Album has been added to your collection')

            data = {
                'created': 'yes',
                'album_title': album.title,
                'album_pk': album.pk
            }
            form = AlbumForm()
        else:
            data = {
                'errors': form.errors
            }
    else:
        data = {'created': 'nothing, you silly goose'}
    return JsonResponse(data)


def create_itunes_album(request):
    if request.method == 'POST':
        data = json.loads(request.body)
        artist_name = data['artist']
        album_title = data['title']
        album_art = data['albumArt']
        album_release = data['releaseDate']
        formatted_release = album_release[:10]
        album_genre = data['albumGenre']

        artist, created = Artist.objects.get_or_create(name=artist_name)

        album_title = data['title']
        album, created = Album.objects.get_or_create(
            title=album_title,
            release_date=formatted_release,
            album_art=album_art
        )

        album.save()
        data = {
            'album_title': album.title,
            'album_artist': artist.name,
            'album_art': album.album_art,
            'album_pk': album.pk,
        }
    else:
        data = {'created': 'nothing'}
    return JsonResponse(data)


def album_edit(request, pk):
    album = get_object_or_404(Album, pk=pk)
    if request.method == "POST":
        form = AlbumForm(request.POST, instance=album)
        if form.is_valid():
            form.save()
            messages.success(request, 'Album has been updated')
            return redirect('album-detail', pk=album.pk)
    else:
        form = AlbumForm(instance=album)
    return render(request, 'music/edit_album.html', {'form': form})


def album_delete(request, pk):
    album = get_object_or_404(Album, pk=pk)
    album.delete()
    messages.error(request, 'Album has been deleted from your collection')
    data = {
        'deleted': 'yes'
    }
    return JsonResponse(data)


def album_delete_detail(request, pk):
    album = get_object_or_404(Album, pk=pk)
    album.delete()
    messages.error(request, 'Album has been deleted from your collection')
    return redirect('home')

music/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" class="has-background-grey-lighter">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/modal.js' %}"></script>
    <script src="{% static 'js/main.js' %}" defer></script>
    <script src="{% static 'js/itunes_API.js' %}" defer></script>
    <title>Jerome's Album Collection</title>
  </head>
  <body id="container" class="container is-fluid">
    <h2 id="page-title" class="title p-4 has-text-centered">
      🎵 🎤 Jerome's Album Collection 🎸 🥁
    </h2>
    {% include 'music/messages.html' %}
    <!-- whatever -->
    {% block content %}
    <!-- whatever -->
    {% endblock %}
    <script>
      setTimeout(function () {
        $('#msg').fadeOut('fast');
      }, 3000);
    </script>
  </body>
</html>

music/templates/music/album_detail.html
{% extends 'base.html' %}
<!-- whatever -->
{% block content %}
<div class="card p-3">
  <div class="card-image">
    <figure class="is-100x100 mb-2">
      <img src="{{ album.album_art }}" alt="Album Art" />
    </figure>
  </div>
  <div class="detail-div">
    <p class="card-title">{{ album }}</p>
    <a href="{% url 'album-edit' pk=album.pk %}" class="button is-dark"> ✎ </a>
    <button
      class="button js-modal-trigger is-danger"
      data-target="modal-delete"
    >
      X
    </button>
    <div id="modal-delete" class="modal m-3">
      <div class="modal-background"></div>
      <div class="modal-card">
        <header class="modal-card-head">
          <p class="modal-card-title">
            Delete <span class="is-italic">{{ album.title }}</span> from your
            collection?
          </p>
          <button class="delete" aria-label="close"></button>
        </header>
        <footer class="modal-card-foot">
          <a
            href="{% url 'album-delete-detail' pk=album.pk %}"
            class="button is-danger"
            >Delete</a
          >
          <button class="button">Cancel</button>
        </footer>
      </div>
    </div>
    <p>Release date: {{ album.release_date }}</p>
    <p>Genre: {{ album.get_genre_display }}</p>
    <p>Track list</p>
    {% for song in album.songs.all %}
    <p>"{{ song.title }}"</p>
    {% endfor %}
  </div>
</div>
{% endblock %}

music/templates/music/edit_album.html
{% extends 'base.html' %}
<!-- whatever -->
{% block content %}
<div class="card p-3">
  <h2>Edit album</h2>
  <form method="POST" class="album-form">
    {% csrf_token %} {{ form.as_p }}
    <button type="submit" class="button is-info is-hovered mt-1">Save</button>
  </form>
</div>
{% endblock %}

music/templates/music/index.html
{% extends 'base.html' %}
<!-- hey Prettier, keep 1 and 3 separate -->
{% block content %}
<!-- This line ^ overwrites what's in this block on base.html -->
<div id="album-list" class="columns">
  {% for album in albums.all %}
  <div class="card column m-3 is-half-tablet is-one-third-desktop">
    <div class="card-image">
      <figure class="is-100x100 mb-2">
        <img src="{{ album.album_art }}" alt="Album Art">
      </figure>
    </div>
    <div class="detail-div">
      <a href="{% url 'album-detail' pk=album.pk %}">{{ album }}</a>
      <a href="{% url 'album-edit' pk=album.pk %}" class="button is-dark"
        >✎</a
      >
      <button
        class="button js-modal-trigger is-danger"
        data-target="{{ album.pk }}"
      >
        X
      </button>
      <div id="{{ album.pk }}" class="modal m-3">
        <div class="modal-background"></div>
        <div class="modal-card">
          <header class="modal-card-head">
            <p class="modal-card-title">
              Delete <span class="is-italic">{{ album.title }}</span> from your collection?
            </p>
            <button class="delete" aria-label="close"></button>
          </header>
          <footer class="modal-card-foot">
            <button data-album-pk="{{ album.pk }}" class="button is-danger delete-button">
              Delete
            </button>
            <button class="button">Cancel</button>
          </footer>
        </div>
      </div>
      <div class="song-list is-flex-direction-column">
        <p>Track list:</p>
      {% for song in album.songs.all %}
      <p>  
      "{{ song.title }}"
      </p>
      {% endfor %}
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<form id="create-form" class="box">
  <h3>Add a new album:</h3>
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="button is-info is-hovered mt-1">Save</button>
</form>
<form id="music-search" class="box" novalidate>
  <h3 id="page-title">iTunes Album Search:</h3>
<div id="search-bar-field" class="mb-1">
  <input id="search-bar" class="container is-fullhd" type="text" placeholder="Search for Cool Albums"></input>
</div>
<div id="submit-field">
  <button id="submit-button" class="button is-info" type="submit">Search</button></div>
</form>
<div id="results-header">
  <h6>Search Results:</h6>
</div>
<div id="search-results" class="results"></div>
{% endblock %}

music/templates/music/messages.html
{% if messages %}
<!-- whatever -->
{% for message in messages %}
<div class="message {{ message.tags }}" id="msg" role="alert">
  {{ message }}
</div>
{% endfor %}
<!-- whatever -->
{% endif %}